apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.deployment }}
  namespace: santiago-parraga-dev
  labels:
    app: {{ .Values.names.app }}
    areanegocio: tecnologia
spec:
  replicas: {{ .Values.labels.minReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.names.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.app }}
    spec:
      containers:
        - name: contenedor-principal
          image: santiagoparraga/holamundobasespm2:build-{{ .Values.container.tag }}  # <-- Reemplaza con la imagen que quieras usar
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
