apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secret }}
  namespace: santiago-parraga-dev
type: Opaque
stringData:
{{- range $k, $v := .Values.secret.stringData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
