apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service }}
  namespace: {{ .Values.namespace }}  # Asegúrate de que coincida con tu Deployment
spec:
  selector:
    app: {{ .Values.names.app }} # Debe coincidir con las labels del Deployment
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}        # Puerto del Service
      targetPort: {{ .Values.service.port }}  # Puerto del contenedor
  type: {{ .Values.service.type }}
